### ISSUE TITLE
configure directory template

### ISSUE THREAD

**Issue by anjohnson** [epics-modules/pcas#1]
I just instantiated the makeBaseApp.pl caServer template from the pcas, which worked fine but there is no top/configure directory or top/Makefile in the template directory so the result is somewhat less useful:
```
tux% ~/epics/base/7.0/bin/linux-x86_64/makeBaseApp.pl -T /home/phoebus/ANJ/epics/base/pcas/templates/makeBaseApp/top -t caServer myServer
tux% ls
myServerApp/
```
This suggests a number of enhancements that would be worth making to the makeBaseApp.pl script so I'm not sure if this really counts as a PCAS bug as such, but it could be fixed by adding files to the template.

**Comment by ralphlange** [comment]
As long as makeBaseApp only understands a single template directory, additional templates from modules will have to be installed in the site's single template directory.
The make run of the module does not know where that place is (might be under EPICS_BASE, might be elsewhere), and it should in no case assume write access to that place or install things outside of INSTALL_LOCATION.
So, under the given circumstances, I only see documentation as a way to resolve this issue.

**Comment by anjohnson** [comment]
… hence my comment about making enhancements to the makeBaseApp.pl script (which would obviously be listed in an issue against Base, not here).

However rather than adding local copies of the template configure files to pcas, the src/template/Makefile could maybe do something like this:

```makefile
BASE_TEMPLATE = $(EPICS_BASE)/templates/$(TEMPLATES_DIR)/top

TEMPLATES += $(BASE_TEMPLATE)/Makefile
TEMPLATES += $(wildcard $(BASE_TEMPLATE)/configure/*)
```

This doesn't work properly right now, but with the addition of a suitable rule something like it could be made to work. I think it's reasonable to copy those template files from Base to ensure that a module's template directory can be used stand-alone, how does that idea strike you?

**Comment by ralphlange** [comment]
I had thought about that, and I don't really like two aspects:
1. If a site has created its own template area, adding things in .../configure (special rules), the module would copy the "wrong" stuff from under EPICS_BASE.
2. It makes it harder to see which parts should be copied to the central single template place (be it under EPICS_BASE or elsewhere).

**Comment by anjohnson** [comment]
If a site has its own template area, they would presumably have EPICS_MBA_TEMPLATE_TOP set in their environment pointing to it. We could do this instead:

```Makefile
EPICS_MBA_TEMPLATE_TOP ?= $(EPICS_BASE)/templates/$(TEMPLATES_DIR)/top

TEMPLATES += $(EPICS_MBA_TEMPLATE_TOP)/Makefile
TEMPLATES += $(wildcard $(EPICS_MBA_TEMPLATE_TOP)/configure/*)
```

That would copy the site's files when that variable is set, or the ones from Base when it isn't. In the first case though users should probably only be using templates from the site's area, so the pcas templates would get installed there by whoever builds pcas and it wouldn't matter what files appear in the pcas/templates tree (so the above change shouldn't be strictly necessary, but the builder still cares about your second aspect).

Of course the above would break if we changed EPICS_MBA_TEMPLATE_TOP to be able to hold a search path instead of just a single directory, but maybe that would need the variable name changing to something like EPICS_MBA_TEMPLATE_PATH. In that case there would be no need to copy the configure files, but under EPICS-7.0.1 the template instantiation is a bit broken.

Hmm, the configure/RELEASE file needs hand-editing anyway to set the path to PCAS which will now be a required dependency for any server tools. I don't see any way to set that automatically without modifying makeBaseApp.pl at the moment, so I'll give up this idea.

Thanks for discussion though, sorry for wasting your evening!
